package controllers

//this code is generated by tools/errorgenerater automatically, don't try to modify it manually !
var mapLanguages = map[string]bool{
	"zh": true,
}

// @Description check if support specific language
func CheckLanguage(lang string) bool {
	if _, ok := mapLanguages[lang]; ok {
		return true
	} else {
		return false
	}
}

// @Description return error message
func ErrorMsg(code ERROR_CODE, lang string) string {
	if _, ok := mapMsgs[code]; ok {
		if _, ok = mapMsgs[code][lang]; ok {
			return mapMsgs[code][lang]
		} else {
			return mapMsgs[ERROR_CODE_UNKNOWN][lang]
		}
	} else {
		return mapMsgs[ERROR_CODE_UNKNOWN][lang]
	}
}

//error code defination
type ERROR_CODE int

const (
	ERROR_CODE_UNKNOWN                                       ERROR_CODE = 0
	ERROR_CODE_DB                                            ERROR_CODE = 1
	ERROR_CODE_REDIS                                         ERROR_CODE = 2
	ERROR_CODE_DECODE_FAILED                                 ERROR_CODE = 3
	ERROR_CODE_GEN_ID                                        ERROR_CODE = 4
	ERROR_CODE_PARAM_FAILED                                  ERROR_CODE = 5
	ERROR_CODE_ENCODE_FAILED                                 ERROR_CODE = 6
	ERROR_CODE_ENCRYPT_FAILED                                ERROR_CODE = 7
	ERROR_CODE_DECRYPT_FAILED                                ERROR_CODE = 8
	ERROR_CODE_SUCCESS                                       ERROR_CODE = 200
	ERROR_CODE_NO_LOGIN                                      ERROR_CODE = 201
	ERROR_CODE_PARAMS_ERROR                                  ERROR_CODE = 202
	ERROR_CODE_NO_USER                                       ERROR_CODE = 203
	ERROR_CODE_CAPTCHA_ERR                                   ERROR_CODE = 204
	ERROR_CODE_SMS_ERR                                       ERROR_CODE = 205
	ERROR_CODE_MOBILE_ERR                                    ERROR_CODE = 206
	ERROR_CODE_SMS_SEND_FAIL                                 ERROR_CODE = 207
	ERROR_CODE_SMS_VERIFY_FAIL_TOO_MATH                      ERROR_CODE = 208
	ERROR_CODE_TOKEN_ERR                                     ERROR_CODE = 209
	ERROR_CODE_CLIENT_TYPE_UNKOWN                            ERROR_CODE = 210
	ERROR_CODE_NO_AUTH                                       ERROR_CODE = 211
	ERROR_CODE_USER_NO_ACTIVE                                ERROR_CODE = 212
	ERROR_CODE_TOKEN_VERIFY_ERR                              ERROR_CODE = 213
	ERROR_CODE_LOGIN_SIGN_VERIFY_ERR                         ERROR_CODE = 214
	ERROR_CODE_PASSWORD_ERR                                  ERROR_CODE = 215
	ERROR_CODE_PASSWORD_FORMAT_ERR                           ERROR_CODE = 216
	ERROR_CODE_PASSWORD_REPEAT_ERR                           ERROR_CODE = 217
	ERROR_CODE_PASSWORD_UNAVAILABLE_ERR                      ERROR_CODE = 218
	ERROR_CODE_PASSWORD_TOKEN_ERR                            ERROR_CODE = 219
	ERROR_CODE_PAY_SIGN_VERIFY_ERR                           ERROR_CODE = 220
	ERROR_CODE_SMS_SEND_REQ_TOO_MUCH                         ERROR_CODE = 221
	ERROR_CODE_PASSWORD_TOKEN_EMPTY                          ERROR_CODE = 222
	ERROR_CODE_UP_FILE_FAIL                                  ERROR_CODE = 223
	ERROR_CODE_APPEAL_SERVICE_LESS                           ERROR_CODE = 224
	ERROR_CODE_PASSWORD_LOCK                                 ERROR_CODE = 225
	ERROR_CODE_UP_FILE_EXT                                   ERROR_CODE = 226
	ERROR_CODE_OTC_ORDER_APPEAL_RESOLVED                     ERROR_CODE = 227
	ERROR_CODE_NEW_MOBILE_ALREADY_PRESENCE                   ERROR_CODE = 228
	ERROR_CODE_USER_UPDATE_MOBILE_FAIL                       ERROR_CODE = 229
	ERROR_CODE_QR_CODE_DECODE_FAIL                           ERROR_CODE = 230
	ERROR_CODE_REQUEST_OUTDATED                              ERROR_CODE = 231
	ERROR_CODE_APPEAL_EXIST                                  ERROR_CODE = 232
	ERROR_CODE_SERVER_STOPPING                               ERROR_CODE = 233
	ERROR_CODE_SERVER_STOPPED                                ERROR_CODE = 234
	ERROR_CODE_SALARY_HAD_GET                                ERROR_CODE = 235
	ERROR_CODE_OTHER_SIDE_APPEAL                             ERROR_CODE = 236
	ERROR_CODE_CAN_NOT_APPEAL                                ERROR_CODE = 237
	ERROR_CODE_PAYMENT_METHOD_UNSUPPORTED                    ERROR_CODE = 400
	ERROR_CODE_PAYMENT_METHOD_CHANGE_STATUS_FAILED           ERROR_CODE = 401
	ERROR_CODE_PAYMENT_METHOD_EDIT_FAILED                    ERROR_CODE = 402
	ERROR_CODE_PAYMENT_METHOD_EDIT_NOTHING                   ERROR_CODE = 403
	ERROR_CODE_PAYMENT_METHOD_OWNER_ERROR                    ERROR_CODE = 404
	ERROR_CODE_PAYMENT_METHOD_UNABLE                         ERROR_CODE = 405
	ERROR_CODE_PAYMENT_METHOD_NO_MATCH                       ERROR_CODE = 406
	ERROR_CODE_USDT_ACCOUNT_NO_FOUND                         ERROR_CODE = 600
	ERROR_CODE_USDT_PRI_KEY_NO_FOUND                         ERROR_CODE = 601
	ERROR_CODE_USDT_ADDRESS_UNAVAILABLE                      ERROR_CODE = 602
	ERROR_CODE_USDT_TRANSFER_FAILED                          ERROR_CODE = 603
	ERROR_CODE_USDT_NO_ENOUGH                                ERROR_CODE = 604
	ERROR_CODE_USDT_MORTGAGE_FAILED                          ERROR_CODE = 605
	ERROR_CODE_USDT_BALANCE_INVALID                          ERROR_CODE = 606
	ERROR_CODE_USDT_CURRENCY_PARAM_ERROR                     ERROR_CODE = 607
	ERROR_CODE_USDT_RELEASE_FAILED                           ERROR_CODE = 608
	ERROR_CODE_USDT_CHAIN_BALANCE_ERROR                      ERROR_CODE = 609
	ERROR_CODE_USDT_CHAIN_TRANSACTION_ERROR                  ERROR_CODE = 610
	ERROR_CODE_USDT_CHAIN_SYNC_TOO_FREQUENTLY                ERROR_CODE = 611
	ERROR_CODE_USDT_CALC_BALANCE_FAILED                      ERROR_CODE = 612
	ERROR_CODE_USDT_GET_SIGNED_TX_FAILED                     ERROR_CODE = 613
	ERROR_CODE_USDT_FROZEN_WEALTH_ERR                        ERROR_CODE = 614
	ERROR_CODE_USDT_USDT_TRANSFER_COMMIT_ERR                 ERROR_CODE = 615
	ERROR_CODE_USDT_REQUEST_FORM_NO_FOUND                    ERROR_CODE = 616
	ERROR_CODE_USDT_CANCEL_FAILED                            ERROR_CODE = 617
	ERROR_CODE_USDT_APPROVE_FAILED                           ERROR_CODE = 618
	ERROR_CODE_USDT_TRANSFER_ON_CHAIN_FAILED                 ERROR_CODE = 619
	ERROR_CODE_USDT_OPRATION_DENY_TRANSFER                   ERROR_CODE = 620
	ERROR_CODE_USDT_CREATE_ACCOUNT_FAILED                    ERROR_CODE = 621
	ERROR_CODE_USDT_WEALTH_LOG_FAILED                        ERROR_CODE = 622
	ERROR_CODE_USDT_CLEAR_FROZEN_FAILED                      ERROR_CODE = 623
	ERROR_CODE_USDT_WEALTH_LOG_STATUS_ERR                    ERROR_CODE = 624
	ERROR_CODE_USDT_QUERY_ONCHAIN_RECHARGE_FAILED            ERROR_CODE = 625
	ERROR_CODE_USDT_DEPOSIT_FAILED                           ERROR_CODE = 626
	ERROR_CODE_USDT_UNFROZEN_FAILED                          ERROR_CODE = 627
	ERROR_CODE_USDT_TRANSFER_TO_SELF_ERR                     ERROR_CODE = 628
	ERROR_CODE_USDT_ACCOUNT_LOCK                             ERROR_CODE = 629
	ERROR_CODE_USDT_TRANSFER_FROZEN_FAILED                   ERROR_CODE = 630
	ERROR_CODE_USDT_TRANSFER_UNFROZEN_FAILED                 ERROR_CODE = 631
	ERROR_CODE_USDT_TRANSFER_CLEAR_FROZEN_FAILED             ERROR_CODE = 632
	ERROR_CODE_USDT_FEE_CURRENCY_PARAM_ERROR                 ERROR_CODE = 633
	ERROR_CODE_USDT_TRANSFER_LOWER_LIMIT_PARAM_ERROR         ERROR_CODE = 634
	ERROR_CODE_USDT_TRANSFER_AMOUNT_LESS_THEN_LOWER_LIMIT    ERROR_CODE = 635
	ERROR_CODE_USDT_TRANSFER_AUDIT_LIMIT_PARAM_ERROR         ERROR_CODE = 636
	ERROR_CODE_USDT_TRANSFER_METHOD_UNSUPPORTED              ERROR_CODE = 637
	ERROR_CODE_USDT_GET_FEE_FAILED                           ERROR_CODE = 640
	ERROR_CODE_GET_BTC_TO_USDT_RATE_FAILED                   ERROR_CODE = 641
	ERROR_CODE_USDT_TRANSFER_TAMPER_PROTECTION_VERIFY_FAILED ERROR_CODE = 650
	ERROR_CODE_USDT_TRANSFER_TAMPERED                        ERROR_CODE = 651
	ERROR_CODE_QUERY_AGENT_FAILED                            ERROR_CODE = 800
	ERROR_CODE_QUERY_AGENT_INVITE_CODE_FAILED                ERROR_CODE = 801
	ERROR_CODE_AGENT_DECREASE_COMMISSION_FAILED              ERROR_CODE = 802
	ERROR_CODE_AGENT_WITHDRAW_ADD_RECORD_FAILED              ERROR_CODE = 803
	ERROR_CODE_AGENT_WITHDRAW_UPDATE_RECORD_STATUS_FAILED    ERROR_CODE = 804
	ERROR_CODE_AGENT_WITHDRAW_QUERY_RECORD_FAILED            ERROR_CODE = 805
	ERROR_CODE_AGENT_WITHDRAW_NO_ENOUGH                      ERROR_CODE = 806
	ERROR_CODE_USER_REGISTERED                               ERROR_CODE = 1001
	ERROR_CODE_REGISTER_ERR                                  ERROR_CODE = 1002
	ERROR_CODE_USER_NEED_INVITE_CODE                         ERROR_CODE = 1003
	ERROR_CODE_USER_INVITE_CODE_ERROR                        ERROR_CODE = 1004
	ERROR_CODE_OTC_APPLY_EXCHANGER_PENDING                   ERROR_CODE = 1500
	ERROR_CODE_OTC_NOT_FOUND_EXCHANGER                       ERROR_CODE = 1501
	ERROR_CODE_OTC_TRADE_TOO_SMALL                           ERROR_CODE = 1502
	ERROR_CODE_OTC_LACK_AVAILABLE_TO_SELL                    ERROR_CODE = 1503
	ERROR_CODE_OTC_DAY_LIMIT_SELL                            ERROR_CODE = 1504
	ERROR_CODE_OTC_ORDER_NOT_FOUND                           ERROR_CODE = 1505
	ERROR_CODE_OTC_ORDER_CANNOT_CANCEL                       ERROR_CODE = 1506
	ERROR_CODE_OTC_ORDER_STATUS_ERR                          ERROR_CODE = 1507
	ERROR_CODE_OTC_BUY_LOWER_LIMIT                           ERROR_CODE = 1508
	ERROR_CODE_OTC_SETTING_ERR                               ERROR_CODE = 1509
	ERROR_CODE_OTC_PAY_TYPE_EMPTY                            ERROR_CODE = 1510
	ERROR_CODE_OTC_PAY_TYPE_ERR                              ERROR_CODE = 1511
	ERROR_CODE_OTC_NOT_MATCH_EXCHANGER                       ERROR_CODE = 1512
	ERROR_CODE_OTC_TRADE_TOO_BIG                             ERROR_CODE = 1513
	ERROR_CODE_OTC_PAYMENT_NOT_FOUND                         ERROR_CODE = 1514
	ERROR_CODE_OTC_LACK_PAYMENT                              ERROR_CODE = 1515
	ERROR_CODE_OTC_ACCOUNT_LOCK                              ERROR_CODE = 1516
	ERROR_CODE_OTC_NOT_A_EXCHANGER                           ERROR_CODE = 1517
	ERROR_CODE_OTC_TRANSFER_AVAILABLE_LACK                   ERROR_CODE = 1518
	ERROR_CODE_REDIS_LOCK_ERR                                ERROR_CODE = 1519
	ERROR_CODE_OP_TOO_FAST                                   ERROR_CODE = 1520
	ERROR_CODE_EUSD_TRANSFER_SELF                            ERROR_CODE = 1521
	ERROR_CODE_SIGN_TRANSACTION_FAIL                         ERROR_CODE = 2001
	ERROR_CODE_GET_BLOCK_INFO_ERROR                          ERROR_CODE = 2002
	ERROR_CODE_PUSH_TRANSACTION_ERROR                        ERROR_CODE = 2003
	ERROR_CODE_ACTION_TO_ABI_ERROR                           ERROR_CODE = 2004
	ERROR_CODE_BUY_RAM_TO_ABI_ERROR                          ERROR_CODE = 2005
	ERROR_CODE_DELEGATE_TO_ABI_ERROR                         ERROR_CODE = 2006
	ERROR_CODE_NEW_ACCOUNT_TO_ABI_ERROR                      ERROR_CODE = 2007
	ERROR_CODE_UNDELEGATE_TO_ABI_ERROR                       ERROR_CODE = 2008
	ERROR_CODE_BIND_WALLET_ERROR                             ERROR_CODE = 2009
	ERROR_CODE_CREATE_ACCOUNT_ERR                            ERROR_CODE = 2010
	ERROR_CODE_UID_PARAMS_ERROR                              ERROR_CODE = 2011
	ERROR_CODE_TRANSFER_LACK_AVAILABLE                       ERROR_CODE = 2012
	ERROR_CODE_TRANSFER_FAIL_LOCK                            ERROR_CODE = 2013
	ERROR_CODE_CONFIG_LACK                                   ERROR_CODE = 2014
	ERROR_CODE_TRANSFER_DB_OUT                               ERROR_CODE = 2015
	ERROR_CODE_TRANSFER_DB_INTO                              ERROR_CODE = 2016
	ERROR_CODE_USER_OTC_ABLE                                 ERROR_CODE = 2017
	ERROR_CODE_WEALTH_LOCK                                   ERROR_CODE = 2018
	ERROR_CODE_QUANTITY_ERR                                  ERROR_CODE = 2019
	ERROR_CODE_EUSD_LACK                                     ERROR_CODE = 2020
	ERROR_CODE_WEALTH_NOT_FOUND                              ERROR_CODE = 2021
	ERROR_CODE_WEALTH_OTC_TRANSFER                           ERROR_CODE = 2022
	ERROR_CODE_OTC_TRANSFER_LOCK                             ERROR_CODE = 2023
	ERROR_CODE_OTC_TRANSFER_UNLOCK                           ERROR_CODE = 2024
	ERROR_CODE_OTC_TRANSFER_OUT                              ERROR_CODE = 2025
	ERROR_CODE_OTC_SET_SELL                                  ERROR_CODE = 2026
	ERROR_CODE_OTC_SET_BUY                                   ERROR_CODE = 2027
	ERROR_CODE_OTC_NOT_EXCHANGER                             ERROR_CODE = 2028
	ERROR_CODE_GAME_SETTLEMENT_ERR                           ERROR_CODE = 2029
	ERROR_CODE_TRANSFER_UNABLE                               ERROR_CODE = 2030
	ERROR_CODE_GAME_UNSUPPORTED_CHANNEL                      ERROR_CODE = 2400
	ERROR_CODE_GAME_CHANNEL_UNSET_RATE                       ERROR_CODE = 2401
	ERROR_CODE_GAME_LOGIN_FAILED                             ERROR_CODE = 2500
	ERROR_CODE_GAME_ADD_USER_FAILED                          ERROR_CODE = 2501
	ERROR_CODE_GAME_USER_NO_EXIST                            ERROR_CODE = 2502
	ERROR_CODE_GAME_ADD_REDEEM_LOG_FAILED                    ERROR_CODE = 2503
	ERROR_CODE_GAME_REDEEM_IN_FAILED                         ERROR_CODE = 2504
	ERROR_CODE_GAME_REDEEM_OUT_FAILED                        ERROR_CODE = 2505
	ERROR_CODE_GAME_ONLINE_PLAYERS_FAILED                    ERROR_CODE = 2506
	ERROR_CODE_GAME_PLAYER_NOT_OFFLINE                       ERROR_CODE = 2507
	ERROR_CODE_GAME_BALANCE_FALIED                           ERROR_CODE = 2508
	ERROR_CODE_SYSTEM_NOTIFICATION_FALIED                    ERROR_CODE = 2801
	ERROR_CODE_SYSTEM_NOTIFICATION_ISREAD_FALIED             ERROR_CODE = 2802
	ERROR_CODE_RECHARGE_AMOUNT_NO_RIGHT                      ERROR_CODE = 2901
	ERROR_CODE_DIVIDEND_TO_AGENT_ERR                         ERROR_CODE = 2902
	ERROR_CODE_NO_FOUND_MONTH_DIVIDEND_RECORD                ERROR_CODE = 2903
	ERROR_CODE_WITHDRAW_MORE_THAN_THRESHOLD                  ERROR_CODE = 2950
	ERROR_CODE_WITHDRAW_FROZEN                               ERROR_CODE = 2951
	ERROR_CODE_PROFIT_THRESHOLD_PARAM_ERROR                  ERROR_CODE = 2952
)

var mapMsgs = map[ERROR_CODE]map[string]string{
	ERROR_CODE_UNKNOWN: {
		"zh": "未知错误",
	}, ERROR_CODE_DB: {
		"zh": "数据库操作错误",
	}, ERROR_CODE_REDIS: {
		"zh": "redis操作错误",
	}, ERROR_CODE_DECODE_FAILED: {
		"zh": "解码失败",
	}, ERROR_CODE_GEN_ID: {
		"zh": "生成唯一标识失败",
	}, ERROR_CODE_PARAM_FAILED: {
		"zh": "获取参数失败",
	}, ERROR_CODE_ENCODE_FAILED: {
		"zh": "编码失败",
	}, ERROR_CODE_ENCRYPT_FAILED: {
		"zh": "加密失败",
	}, ERROR_CODE_DECRYPT_FAILED: {
		"zh": "解密失败",
	}, ERROR_CODE_SUCCESS: {}, ERROR_CODE_NO_LOGIN: {
		"zh": "请先登录",
	}, ERROR_CODE_PARAMS_ERROR: {
		"zh": "参数错误",
	}, ERROR_CODE_NO_USER: {
		"zh": "用户不存在",
	}, ERROR_CODE_CAPTCHA_ERR: {
		"zh": "验证码错误",
	}, ERROR_CODE_SMS_ERR: {
		"zh": "短信验证码错误",
	}, ERROR_CODE_MOBILE_ERR: {
		"zh": "手机号错误",
	}, ERROR_CODE_SMS_SEND_FAIL: {
		"zh": "短信验证码发送失败",
	}, ERROR_CODE_SMS_VERIFY_FAIL_TOO_MATH: {
		"zh": "短信验证码验证失败次数太多，请重新获取短信",
	}, ERROR_CODE_TOKEN_ERR: {
		"zh": "Token生成失败",
	}, ERROR_CODE_CLIENT_TYPE_UNKOWN: {
		"zh": "客户端类型未知",
	}, ERROR_CODE_NO_AUTH: {
		"zh": "没有权限",
	}, ERROR_CODE_USER_NO_ACTIVE: {
		"zh": "您被禁止登录了，如有疑问，请联系客服",
	}, ERROR_CODE_TOKEN_VERIFY_ERR: {
		"zh": "登录TOKEN验证失败，请重新登录",
	}, ERROR_CODE_LOGIN_SIGN_VERIFY_ERR: {
		"zh": "认证信息已过期，请重新登录",
	}, ERROR_CODE_PASSWORD_ERR: {
		"zh": "密码错误",
	}, ERROR_CODE_PASSWORD_FORMAT_ERR: {
		"zh": "密码格式错误",
	}, ERROR_CODE_PASSWORD_REPEAT_ERR: {
		"zh": "新旧密码不能相同",
	}, ERROR_CODE_PASSWORD_UNAVAILABLE_ERR: {
		"zh": "支付密码未设置或不可用，请设置支付密码",
	}, ERROR_CODE_PASSWORD_TOKEN_ERR: {
		"zh": "支付密码验证信息已过期",
	}, ERROR_CODE_PAY_SIGN_VERIFY_ERR: {
		"zh": "认证信息已过期，请使用支付密码认证",
	}, ERROR_CODE_SMS_SEND_REQ_TOO_MUCH: {
		"zh": "请不要频繁操作",
	}, ERROR_CODE_PASSWORD_TOKEN_EMPTY: {
		"zh": "请输入支付密码",
	}, ERROR_CODE_UP_FILE_FAIL: {
		"zh": "文件上传失败",
	}, ERROR_CODE_APPEAL_SERVICE_LESS: {
		"zh": "当前客服繁忙,请稍后再试",
	}, ERROR_CODE_PASSWORD_LOCK: {
		"zh": "支付密码已被锁定，请5分钟后再试",
	}, ERROR_CODE_UP_FILE_EXT: {
		"zh": "请选择正确格式的文件",
	}, ERROR_CODE_OTC_ORDER_APPEAL_RESOLVED: {
		"zh": "申述已解决,请不要重复操作",
	}, ERROR_CODE_NEW_MOBILE_ALREADY_PRESENCE: {
		"zh": "新手机号已存在",
	}, ERROR_CODE_USER_UPDATE_MOBILE_FAIL: {
		"zh": "用户更新手机号失败",
	}, ERROR_CODE_QR_CODE_DECODE_FAIL: {
		"zh": "二维码解析失败,请检查",
	}, ERROR_CODE_REQUEST_OUTDATED: {
		"zh": "请求超过有效时间",
	}, ERROR_CODE_APPEAL_EXIST: {
		"zh": "订单已申诉,正在处理中",
	}, ERROR_CODE_SERVER_STOPPING: {
		"zh": "服务器将进行维护,无法本操作",
	}, ERROR_CODE_SERVER_STOPPED: {
		"zh": "服务器正在维护中",
	}, ERROR_CODE_SALARY_HAD_GET: {
		"zh": "已领取",
	}, ERROR_CODE_OTHER_SIDE_APPEAL: {
		"zh": "订单申诉中,非申诉方请联系客服",
	}, ERROR_CODE_CAN_NOT_APPEAL: {
		"zh": "订单状态不可申诉",
	}, ERROR_CODE_PAYMENT_METHOD_UNSUPPORTED: {
		"zh": "不支持的收付款类型",
	}, ERROR_CODE_PAYMENT_METHOD_CHANGE_STATUS_FAILED: {
		"zh": "修改收付款方式状态失败",
	}, ERROR_CODE_PAYMENT_METHOD_EDIT_FAILED: {
		"zh": "编辑收付款方式失败",
	}, ERROR_CODE_PAYMENT_METHOD_EDIT_NOTHING: {
		"zh": "收付款方式属性无修改",
	}, ERROR_CODE_PAYMENT_METHOD_OWNER_ERROR: {
		"zh": "非该收付款方式拥有者",
	}, ERROR_CODE_PAYMENT_METHOD_UNABLE: {
		"zh": "收付款方式不可用",
	}, ERROR_CODE_PAYMENT_METHOD_NO_MATCH: {
		"zh": "收付款方式不可用",
	}, ERROR_CODE_USDT_ACCOUNT_NO_FOUND: {
		"zh": "usdt账户不存在",
	}, ERROR_CODE_USDT_PRI_KEY_NO_FOUND: {
		"zh": "usdt账户对应的密钥不存在",
	}, ERROR_CODE_USDT_ADDRESS_UNAVAILABLE: {
		"zh": "usdt地址不可用",
	}, ERROR_CODE_USDT_TRANSFER_FAILED: {
		"zh": "usdt转账失败",
	}, ERROR_CODE_USDT_NO_ENOUGH: {
		"zh": "usdt余额不足",
	}, ERROR_CODE_USDT_MORTGAGE_FAILED: {
		"zh": "usdt抵押失败",
	}, ERROR_CODE_USDT_BALANCE_INVALID: {
		"zh": "usdt资产数据不可用",
	}, ERROR_CODE_USDT_CURRENCY_PARAM_ERROR: {
		"zh": "usdt金额参数错误",
	}, ERROR_CODE_USDT_RELEASE_FAILED: {
		"zh": "usdt赎回失败",
	}, ERROR_CODE_USDT_CHAIN_BALANCE_ERROR: {
		"zh": "usdt链上账户数据错误",
	}, ERROR_CODE_USDT_CHAIN_TRANSACTION_ERROR: {
		"zh": "usdt链上交易数据错误",
	}, ERROR_CODE_USDT_CHAIN_SYNC_TOO_FREQUENTLY: {
		"zh": "usdt同步链上交易数据过于频繁",
	}, ERROR_CODE_USDT_CALC_BALANCE_FAILED: {
		"zh": "usdt演算账户金额失败",
	}, ERROR_CODE_USDT_GET_SIGNED_TX_FAILED: {
		"zh": "usdt获取离线签名交易数据失败",
	}, ERROR_CODE_USDT_FROZEN_WEALTH_ERR: {
		"zh": "usdt资金冻结失败",
	}, ERROR_CODE_USDT_USDT_TRANSFER_COMMIT_ERR: {
		"zh": "usdt转账申请失败,请联系客服",
	}, ERROR_CODE_USDT_REQUEST_FORM_NO_FOUND: {
		"zh": "申请单不存在",
	}, ERROR_CODE_USDT_CANCEL_FAILED: {
		"zh": "取消申请单失败",
	}, ERROR_CODE_USDT_APPROVE_FAILED: {
		"zh": "审批失败",
	}, ERROR_CODE_USDT_TRANSFER_ON_CHAIN_FAILED: {
		"zh": "推送交易失败",
	}, ERROR_CODE_USDT_OPRATION_DENY_TRANSFER: {
		"zh": "暂未开放手机号转账",
	}, ERROR_CODE_USDT_CREATE_ACCOUNT_FAILED: {
		"zh": "usdt账户创建失败",
	}, ERROR_CODE_USDT_WEALTH_LOG_FAILED: {
		"zh": "usdt记录资产日志失败",
	}, ERROR_CODE_USDT_CLEAR_FROZEN_FAILED: {
		"zh": "usdt清除冻结资产失败",
	}, ERROR_CODE_USDT_WEALTH_LOG_STATUS_ERR: {
		"zh": "usdt订单状态错误",
	}, ERROR_CODE_USDT_QUERY_ONCHAIN_RECHARGE_FAILED: {
		"zh": "usdt获取链上充值数据失败",
	}, ERROR_CODE_USDT_DEPOSIT_FAILED: {
		"zh": "usdt修改充值数据失败",
	}, ERROR_CODE_USDT_UNFROZEN_FAILED: {
		"zh": "usdt解冻资产失败",
	}, ERROR_CODE_USDT_TRANSFER_TO_SELF_ERR: {
		"zh": "usdt无法给自己转账",
	}, ERROR_CODE_USDT_ACCOUNT_LOCK: {
		"zh": "账号被锁定",
	}, ERROR_CODE_USDT_TRANSFER_FROZEN_FAILED: {
		"zh": "交易资金冻结失败",
	}, ERROR_CODE_USDT_TRANSFER_UNFROZEN_FAILED: {
		"zh": "交易资金解冻失败",
	}, ERROR_CODE_USDT_TRANSFER_CLEAR_FROZEN_FAILED: {
		"zh": "交易资金清除失败",
	}, ERROR_CODE_USDT_FEE_CURRENCY_PARAM_ERROR: {
		"zh": "usdt手续费金额参数错误",
	}, ERROR_CODE_USDT_TRANSFER_LOWER_LIMIT_PARAM_ERROR: {
		"zh": "usdt转账最低限额获取失败",
	}, ERROR_CODE_USDT_TRANSFER_AMOUNT_LESS_THEN_LOWER_LIMIT: {
		"zh": "usdt转账金额小于最低限额",
	}, ERROR_CODE_USDT_TRANSFER_AUDIT_LIMIT_PARAM_ERROR: {
		"zh": "usdt转账金额免审核配置获取失败",
	}, ERROR_CODE_USDT_TRANSFER_METHOD_UNSUPPORTED: {
		"zh": "未知的转账方式",
	}, ERROR_CODE_USDT_GET_FEE_FAILED: {
		"zh": "获取推荐手续费失败",
	}, ERROR_CODE_GET_BTC_TO_USDT_RATE_FAILED: {
		"zh": "获取推荐手续费失败",
	}, ERROR_CODE_USDT_TRANSFER_TAMPER_PROTECTION_VERIFY_FAILED: {
		"zh": "交易数据防篡改校验失败",
	}, ERROR_CODE_USDT_TRANSFER_TAMPERED: {
		"zh": "交易数据遭篡改",
	}, ERROR_CODE_QUERY_AGENT_FAILED: {
		"zh": "查询用户代理信息失败",
	}, ERROR_CODE_QUERY_AGENT_INVITE_CODE_FAILED: {
		"zh": "查询用户邀请码信息失败",
	}, ERROR_CODE_AGENT_DECREASE_COMMISSION_FAILED: {
		"zh": "扣除用户佣金失败",
	}, ERROR_CODE_AGENT_WITHDRAW_ADD_RECORD_FAILED: {
		"zh": "增加佣金提现记录失败",
	}, ERROR_CODE_AGENT_WITHDRAW_UPDATE_RECORD_STATUS_FAILED: {
		"zh": "更新佣金提现记录状态失败",
	}, ERROR_CODE_AGENT_WITHDRAW_QUERY_RECORD_FAILED: {
		"zh": "查询佣金提现记录失败",
	}, ERROR_CODE_AGENT_WITHDRAW_NO_ENOUGH: {
		"zh": "佣金提现金额不足",
	}, ERROR_CODE_USER_REGISTERED: {
		"zh": "用户已经注册过",
	}, ERROR_CODE_REGISTER_ERR: {
		"zh": "注册失败",
	}, ERROR_CODE_USER_NEED_INVITE_CODE: {
		"zh": "请输入邀请码",
	}, ERROR_CODE_USER_INVITE_CODE_ERROR: {
		"zh": "请输入正确的邀请码",
	}, ERROR_CODE_OTC_APPLY_EXCHANGER_PENDING: {
		"zh": "你的申请正在处理中",
	}, ERROR_CODE_OTC_NOT_FOUND_EXCHANGER: {
		"zh": "没有找到承兑商",
	}, ERROR_CODE_OTC_TRADE_TOO_SMALL: {
		"zh": "设置的交易金额太小 金额要大于100CNY",
	}, ERROR_CODE_OTC_LACK_AVAILABLE_TO_SELL: {
		"zh": "可以出售的EUSD太少了",
	}, ERROR_CODE_OTC_DAY_LIMIT_SELL: {
		"zh": "达到今日出售限额",
	}, ERROR_CODE_OTC_ORDER_NOT_FOUND: {
		"zh": "没有找到订单",
	}, ERROR_CODE_OTC_ORDER_CANNOT_CANCEL: {
		"zh": "订单不能取消",
	}, ERROR_CODE_OTC_ORDER_STATUS_ERR: {
		"zh": "订单状态异常",
	}, ERROR_CODE_OTC_BUY_LOWER_LIMIT: {
		"zh": "购买达到限额",
	}, ERROR_CODE_OTC_SETTING_ERR: {
		"zh": "设置失败",
	}, ERROR_CODE_OTC_PAY_TYPE_EMPTY: {
		"zh": "支付方式为空",
	}, ERROR_CODE_OTC_PAY_TYPE_ERR: {
		"zh": "支付方式错误",
	}, ERROR_CODE_OTC_NOT_MATCH_EXCHANGER: {
		"zh": "没有找到合适的承兑商",
	}, ERROR_CODE_OTC_TRADE_TOO_BIG: {
		"zh": "交易金额超过限额",
	}, ERROR_CODE_OTC_PAYMENT_NOT_FOUND: {
		"zh": "未找到收付款方式",
	}, ERROR_CODE_OTC_LACK_PAYMENT: {
		"zh": "缺少支付方式或者支付方式都已经达到限额了",
	}, ERROR_CODE_OTC_ACCOUNT_LOCK: {
		"zh": "账号被锁定",
	}, ERROR_CODE_OTC_NOT_A_EXCHANGER: {
		"zh": "你不是一个承兑商",
	}, ERROR_CODE_OTC_TRANSFER_AVAILABLE_LACK: {
		"zh": "余额不足",
	}, ERROR_CODE_REDIS_LOCK_ERR: {
		"zh": "操作超时（Lock）",
	}, ERROR_CODE_OP_TOO_FAST: {
		"zh": "操作太快",
	}, ERROR_CODE_EUSD_TRANSFER_SELF: {
		"zh": "不能自己转账给自己",
	}, ERROR_CODE_SIGN_TRANSACTION_FAIL: {
		"zh": "交易签名失败",
	}, ERROR_CODE_GET_BLOCK_INFO_ERROR: {
		"zh": "获取区块信息失败",
	}, ERROR_CODE_PUSH_TRANSACTION_ERROR: {
		"zh": "推送交易失败",
	}, ERROR_CODE_ACTION_TO_ABI_ERROR: {
		"zh": "转换ABI失败",
	}, ERROR_CODE_BUY_RAM_TO_ABI_ERROR: {
		"zh": "购买RAM转换ABI失败",
	}, ERROR_CODE_DELEGATE_TO_ABI_ERROR: {
		"zh": "抵押转换ABI失败",
	}, ERROR_CODE_NEW_ACCOUNT_TO_ABI_ERROR: {
		"zh": "创建账号转换ABI失败",
	}, ERROR_CODE_UNDELEGATE_TO_ABI_ERROR: {
		"zh": "赎回转换ABI失败",
	}, ERROR_CODE_BIND_WALLET_ERROR: {
		"zh": "绑定钱包失败",
	}, ERROR_CODE_CREATE_ACCOUNT_ERR: {
		"zh": "生成新钱包账号失败",
	}, ERROR_CODE_UID_PARAMS_ERROR: {
		"zh": "UID 参数错误",
	}, ERROR_CODE_TRANSFER_LACK_AVAILABLE: {
		"zh": "可用TOKEN不足",
	}, ERROR_CODE_TRANSFER_FAIL_LOCK: {
		"zh": "转账锁定失败，请重试",
	}, ERROR_CODE_CONFIG_LACK: {
		"zh": "配置信息缺失",
	}, ERROR_CODE_TRANSFER_DB_OUT: {
		"zh": "出账失败（DB）",
	}, ERROR_CODE_TRANSFER_DB_INTO: {
		"zh": "入账失败（DB）",
	}, ERROR_CODE_USER_OTC_ABLE: {
		"zh": "用户成为承兑商错误",
	}, ERROR_CODE_WEALTH_LOCK: {
		"zh": "账户被冻结",
	}, ERROR_CODE_QUANTITY_ERR: {
		"zh": "数量不正确",
	}, ERROR_CODE_EUSD_LACK: {
		"zh": "币数量不足",
	}, ERROR_CODE_WEALTH_NOT_FOUND: {
		"zh": "未找到账号信息",
	}, ERROR_CODE_WEALTH_OTC_TRANSFER: {
		"zh": "划转失败",
	}, ERROR_CODE_OTC_TRANSFER_LOCK: {
		"zh": "OTC冻结资金失败",
	}, ERROR_CODE_OTC_TRANSFER_UNLOCK: {
		"zh": "OTC解冻资金失败",
	}, ERROR_CODE_OTC_TRANSFER_OUT: {
		"zh": "OTC转账失败",
	}, ERROR_CODE_OTC_SET_SELL: {
		"zh": "设置出售失败，请重试",
	}, ERROR_CODE_OTC_SET_BUY: {
		"zh": "设置买入失败，请重试",
	}, ERROR_CODE_OTC_NOT_EXCHANGER: {
		"zh": "用户不是承兑商",
	}, ERROR_CODE_GAME_SETTLEMENT_ERR: {
		"zh": "游戏结算异常",
	}, ERROR_CODE_TRANSFER_UNABLE: {
		"zh": "被禁止进行交易动作",
	}, ERROR_CODE_GAME_UNSUPPORTED_CHANNEL: {
		"zh": "不支持的游戏渠道",
	}, ERROR_CODE_GAME_CHANNEL_UNSET_RATE: {
		"zh": "游戏渠道未设置充值比率",
	}, ERROR_CODE_GAME_LOGIN_FAILED: {
		"zh": "游戏登录失败",
	}, ERROR_CODE_GAME_ADD_USER_FAILED: {
		"zh": "增加游戏账户失败",
	}, ERROR_CODE_GAME_USER_NO_EXIST: {
		"zh": "游戏账户不存在",
	}, ERROR_CODE_GAME_ADD_REDEEM_LOG_FAILED: {
		"zh": "增加游戏转账记录失败",
	}, ERROR_CODE_GAME_REDEEM_IN_FAILED: {
		"zh": "游戏账户存款失败",
	}, ERROR_CODE_GAME_REDEEM_OUT_FAILED: {
		"zh": "游戏账户提款失败",
	}, ERROR_CODE_GAME_ONLINE_PLAYERS_FAILED: {
		"zh": "查询游戏在线玩家失败",
	}, ERROR_CODE_GAME_PLAYER_NOT_OFFLINE: {
		"zh": "游戏玩家当前在线",
	}, ERROR_CODE_GAME_BALANCE_FALIED: {
		"zh": "获取游戏玩家余额信息失败",
	}, ERROR_CODE_SYSTEM_NOTIFICATION_FALIED: {
		"zh": "获取系统消息失败",
	}, ERROR_CODE_SYSTEM_NOTIFICATION_ISREAD_FALIED: {
		"zh": "获取系统通知已读失败",
	}, ERROR_CODE_RECHARGE_AMOUNT_NO_RIGHT: {
		"zh": "重置金额不足以还清所欠的eusd",
	}, ERROR_CODE_DIVIDEND_TO_AGENT_ERR: {
		"zh": "分发月分红给下级代理失败",
	}, ERROR_CODE_NO_FOUND_MONTH_DIVIDEND_RECORD: {
		"zh": "未找到月分红记录",
	}, ERROR_CODE_WITHDRAW_MORE_THAN_THRESHOLD: {
		"zh": "提现金额超过阈值",
	}, ERROR_CODE_WITHDRAW_FROZEN: {
		"zh": "有待审核的提现记录,提现功能暂时冻结,请联系客服",
	}, ERROR_CODE_PROFIT_THRESHOLD_PARAM_ERROR: {
		"zh": "分润阈值配置获取失败",
	},
}
