// Code generated by MockGen. DO NOT EDIT.
// Source: onchain_data.go

// Package mock_dao is a generated GoMock package.
package mock_dao

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockOnchainDataDaoInterface is a mock of OnchainDataDaoInterface interface
type MockOnchainDataDaoInterface struct {
	ctrl     *gomock.Controller
	recorder *MockOnchainDataDaoInterfaceMockRecorder
}

// MockOnchainDataDaoInterfaceMockRecorder is the mock recorder for MockOnchainDataDaoInterface
type MockOnchainDataDaoInterfaceMockRecorder struct {
	mock *MockOnchainDataDaoInterface
}

// NewMockOnchainDataDaoInterface creates a new mock instance
func NewMockOnchainDataDaoInterface(ctrl *gomock.Controller) *MockOnchainDataDaoInterface {
	mock := &MockOnchainDataDaoInterface{ctrl: ctrl}
	mock.recorder = &MockOnchainDataDaoInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockOnchainDataDaoInterface) EXPECT() *MockOnchainDataDaoInterfaceMockRecorder {
	return m.recorder
}

// SetLastestTransaction mocks base method
func (m *MockOnchainDataDaoInterface) SetLastestTransaction(addr, tx string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetLastestTransaction", addr, tx)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetLastestTransaction indicates an expected call of SetLastestTransaction
func (mr *MockOnchainDataDaoInterfaceMockRecorder) SetLastestTransaction(addr, tx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetLastestTransaction", reflect.TypeOf((*MockOnchainDataDaoInterface)(nil).SetLastestTransaction), addr, tx)
}

// GetLastestTransaction mocks base method
func (m *MockOnchainDataDaoInterface) GetLastestTransaction(addr string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastestTransaction", addr)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLastestTransaction indicates an expected call of GetLastestTransaction
func (mr *MockOnchainDataDaoInterfaceMockRecorder) GetLastestTransaction(addr interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastestTransaction", reflect.TypeOf((*MockOnchainDataDaoInterface)(nil).GetLastestTransaction), addr)
}
