// Code generated by protoc-gen-go. DO NOT EDIT.
// source: agent_path.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// AgentPath
type AgentPath struct {
	PUId                 uint64   `protobuf:"varint,1,opt,name=PUId,proto3" json:"PUId,omitempty"`
	Level                uint32   `protobuf:"varint,2,opt,name=Level,proto3" json:"Level,omitempty"`
	SubUid               []uint64 `protobuf:"varint,3,rep,packed,name=SubUid,proto3" json:"SubUid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AgentPath) Reset()         { *m = AgentPath{} }
func (m *AgentPath) String() string { return proto.CompactTextString(m) }
func (*AgentPath) ProtoMessage()    {}
func (*AgentPath) Descriptor() ([]byte, []int) {
	return fileDescriptor_bedf5b1ac52d4e0e, []int{0}
}

func (m *AgentPath) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AgentPath.Unmarshal(m, b)
}
func (m *AgentPath) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AgentPath.Marshal(b, m, deterministic)
}
func (m *AgentPath) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AgentPath.Merge(m, src)
}
func (m *AgentPath) XXX_Size() int {
	return xxx_messageInfo_AgentPath.Size(m)
}
func (m *AgentPath) XXX_DiscardUnknown() {
	xxx_messageInfo_AgentPath.DiscardUnknown(m)
}

var xxx_messageInfo_AgentPath proto.InternalMessageInfo

func (m *AgentPath) GetPUId() uint64 {
	if m != nil {
		return m.PUId
	}
	return 0
}

func (m *AgentPath) GetLevel() uint32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *AgentPath) GetSubUid() []uint64 {
	if m != nil {
		return m.SubUid
	}
	return nil
}

func init() {
	proto.RegisterType((*AgentPath)(nil), "pb.AgentPath")
}

func init() { proto.RegisterFile("agent_path.proto", fileDescriptor_bedf5b1ac52d4e0e) }

var fileDescriptor_bedf5b1ac52d4e0e = []byte{
	// 115 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x48, 0x4c, 0x4f, 0xcd,
	0x2b, 0x89, 0x2f, 0x48, 0x2c, 0xc9, 0xd0, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2a, 0x48,
	0x52, 0xf2, 0xe5, 0xe2, 0x74, 0x04, 0x89, 0x07, 0x24, 0x96, 0x64, 0x08, 0x09, 0x71, 0xb1, 0x04,
	0x84, 0x7a, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x04, 0x81, 0xd9, 0x42, 0x22, 0x5c, 0xac,
	0x3e, 0xa9, 0x65, 0xa9, 0x39, 0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0xbc, 0x41, 0x10, 0x8e, 0x90, 0x18,
	0x17, 0x5b, 0x70, 0x69, 0x52, 0x68, 0x66, 0x8a, 0x04, 0xb3, 0x02, 0xb3, 0x06, 0x4b, 0x10, 0x94,
	0x97, 0xc4, 0x06, 0x36, 0xd9, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0xa2, 0x45, 0x38, 0xaf, 0x6d,
	0x00, 0x00, 0x00,
}
