package controllers

//this code is generated by tools/errorgenerater automatically, don't try to modify it manually !
var mapLanguages = map[string]bool{
	"zh": true,
}

// @Description check if support specific language
func CheckLanguage(lang string) bool {
	if _, ok := mapLanguages[lang]; ok {
		return true
	} else {
		return false
	}
}

// @Description return error message
func ErrorMsg(code ERROR_CODE, lang string) string {
	if _, ok := mapMsgs[code]; ok {
		if _, ok = mapMsgs[code][lang]; ok {
			return mapMsgs[code][lang]
		} else {
			return mapMsgs[ERROR_CODE_UNKNOWN][lang]
		}
	} else {
		return mapMsgs[ERROR_CODE_UNKNOWN][lang]
	}
}

//error code defination
type ERROR_CODE int

const (
	ERROR_CODE_UNKNOWN                                    ERROR_CODE = 0
	ERROR_CODE_DB                                         ERROR_CODE = 1
	ERROR_CODE_PARAM_FAILED                               ERROR_CODE = 2
	ERROR_CODE_NO_SYSMSG                                  ERROR_CODE = 3
	ERROR_CODE_DEL_FAIL                                   ERROR_CODE = 4
	ERROR_CODE_UPDATE_FAIL                                ERROR_CODE = 5
	ERROR_CODE_SIGN_FAIL                                  ERROR_CODE = 6
	ERROR_CODE_OTC_REQ_FAIL                               ERROR_CODE = 7
	ERROR_CODE_GEN_GOOGLE_AUTH_FAIL                       ERROR_CODE = 8
	ERROR_CODE_RABBIT_MQ_PUBLISH_FAIL                     ERROR_CODE = 9
	ERROR_CODE_ENCODE_FAIL                                ERROR_CODE = 10
	ERROR_CODE_DECODE_FAIL                                ERROR_CODE = 11
	ERROR_CODE_SUCCESS                                    ERROR_CODE = 200
	ERROR_CODE_NO_LOGIN                                   ERROR_CODE = 201
	ERROR_CODE_PARAMS_ERROR                               ERROR_CODE = 202
	ERROR_CODE_NO_USER                                    ERROR_CODE = 203
	ERROR_CODE_CAPTCHA_ERR                                ERROR_CODE = 204
	ERROR_CODE_TOKEN_ERR                                  ERROR_CODE = 205
	ERROR_CODE_PWD_ERROR                                  ERROR_CODE = 206
	ERROR_CODE_DB_NO_DATA                                 ERROR_CODE = 207
	ERROR_CODE_USER_NAME_ERROR                            ERROR_CODE = 208
	ERROR_CODE_USER_NO_ACTIVE                             ERROR_CODE = 209
	ERROR_CODE_ID_EXSIT                                   ERROR_CODE = 210
	ERROR_CODE_TOKEN_VERIFY_ERR                           ERROR_CODE = 211
	ERROR_CODE_MOBILE_EXSIT                               ERROR_CODE = 212
	ERROR_CODE_MOBILE_REGISTERED                          ERROR_CODE = 213
	ERROR_CODE_COMMISSION_DISTRIBUTE_FAIL                 ERROR_CODE = 214
	ERROR_CODE_APPEAL_SERVICE_LESS                        ERROR_CODE = 215
	ERROR_CODE_CANCEL_ORDER_FAIL                          ERROR_CODE = 216
	ERROR_CODE_CONFIRM_ORDER_FAIL                         ERROR_CODE = 217
	ERROR_CODE_EXIST_WHITE_LIST_AGENT                     ERROR_CODE = 218
	ERROR_CODE_OTC_FAIL                                   ERROR_CODE = 219
	ERROR_CODE_OTC_ORDER_STATUS_ERR                       ERROR_CODE = 220
	ERROR_CODE_OTC_ORDER_APPEAL_RESOLVED                  ERROR_CODE = 221
	ERROR_CODE_VERITY_GOOGLE_CODE_FAIL                    ERROR_CODE = 222
	ERROR_CODE_SMS_NO_SUPPORT_CHINA_MOBILE                ERROR_CODE = 223
	ERROR_CODE_HAS_LOWER_LEVEL                            ERROR_CODE = 224
	ERROR_CODE_NO_RIGHT_ERROR                             ERROR_CODE = 403
	ERROR_CODE_TASK_NO_EXIST_ERROR                        ERROR_CODE = 600
	ERROR_CODE_TASK_STATUS_ERROR                          ERROR_CODE = 601
	ERROR_CODE_TASK_APPNAME_DIFFERENT_ERROR               ERROR_CODE = 602
	ERROR_CODE_AGENT_WITHDRAW_NO_ENOUGH                   ERROR_CODE = 801
	ERROR_CODE_AGENT_DECREASE_COMMISSION_FAILED           ERROR_CODE = 802
	ERROR_CODE_AGENT_WITHDRAW_ADD_RECORD_FAILED           ERROR_CODE = 803
	ERROR_CODE_AGENT_WITHDRAW_UPDATE_RECORD_STATUS_FAILED ERROR_CODE = 804
	ERROR_CODE_AGENT_WITHDRAW_QUERY_RECORD_FAILED         ERROR_CODE = 805
	ERROR_CODE_AGENT_WITHDRAW_CHECKED                     ERROR_CODE = 806
	ERROR_CODE_USER_REGISTERED                            ERROR_CODE = 1001
	ERROR_CODE_RISK_ALERT                                 ERROR_CODE = 1002
	ERROR_CODE_GAME_REPORT_CAL                            ERROR_CODE = 1003
	ERROR_CODE_GAME_DATA_HASED                            ERROR_CODE = 1004
)

var mapMsgs = map[ERROR_CODE]map[string]string{
	ERROR_CODE_UNKNOWN: {
		"zh": "未知错误",
	}, ERROR_CODE_DB: {
		"zh": "数据库操作错误",
	}, ERROR_CODE_PARAM_FAILED: {
		"zh": "获取参数失败",
	}, ERROR_CODE_NO_SYSMSG: {
		"zh": "未匹配到该id的系统消息",
	}, ERROR_CODE_DEL_FAIL: {
		"zh": "数据库删除失败",
	}, ERROR_CODE_UPDATE_FAIL: {
		"zh": "数据库更新失败",
	}, ERROR_CODE_SIGN_FAIL: {
		"zh": "签名失败",
	}, ERROR_CODE_OTC_REQ_FAIL: {
		"zh": "otc请求失败",
	}, ERROR_CODE_GEN_GOOGLE_AUTH_FAIL: {
		"zh": "google验证生成失败",
	}, ERROR_CODE_RABBIT_MQ_PUBLISH_FAIL: {
		"zh": "rabbitmq发送消息失败",
	}, ERROR_CODE_ENCODE_FAIL: {
		"zh": "编码失败",
	}, ERROR_CODE_DECODE_FAIL: {
		"zh": "解码失败",
	}, ERROR_CODE_SUCCESS: {}, ERROR_CODE_NO_LOGIN: {
		"zh": "请先登录",
	}, ERROR_CODE_PARAMS_ERROR: {
		"zh": "参数错误",
	}, ERROR_CODE_NO_USER: {
		"zh": "用户不存在",
	}, ERROR_CODE_CAPTCHA_ERR: {
		"zh": "验证码错误",
	}, ERROR_CODE_TOKEN_ERR: {
		"zh": "Token生成失败",
	}, ERROR_CODE_PWD_ERROR: {
		"zh": "密码错误",
	}, ERROR_CODE_DB_NO_DATA: {
		"zh": "未找到数据",
	}, ERROR_CODE_USER_NAME_ERROR: {
		"zh": "请输入合法的用户名",
	}, ERROR_CODE_USER_NO_ACTIVE: {
		"zh": "用户未激活",
	}, ERROR_CODE_ID_EXSIT: {
		"zh": "ID已存在",
	}, ERROR_CODE_TOKEN_VERIFY_ERR: {
		"zh": "登录TOKEN验证失败，请重新登录",
	}, ERROR_CODE_MOBILE_EXSIT: {
		"zh": "手机号已存在",
	}, ERROR_CODE_MOBILE_REGISTERED: {
		"zh": "手机号已在列表或者已注册,不能修改",
	}, ERROR_CODE_COMMISSION_DISTRIBUTE_FAIL: {
		"zh": "佣金发放失败",
	}, ERROR_CODE_APPEAL_SERVICE_LESS: {
		"zh": "请保证至少启用一个申诉客服",
	}, ERROR_CODE_CANCEL_ORDER_FAIL: {
		"zh": "取消订单失败",
	}, ERROR_CODE_CONFIRM_ORDER_FAIL: {
		"zh": "确认订单失败",
	}, ERROR_CODE_EXIST_WHITE_LIST_AGENT: {
		"zh": "已有档位,不能添加",
	}, ERROR_CODE_OTC_FAIL: {
		"zh": "OTC处理失败",
	}, ERROR_CODE_OTC_ORDER_STATUS_ERR: {
		"zh": "订单状态异常",
	}, ERROR_CODE_OTC_ORDER_APPEAL_RESOLVED: {
		"zh": "申述已解决,请不要重复操作",
	}, ERROR_CODE_VERITY_GOOGLE_CODE_FAIL: {
		"zh": "验证码错误,请同步手机时间后重新输入",
	}, ERROR_CODE_SMS_NO_SUPPORT_CHINA_MOBILE: {
		"zh": "不支持国内手机号发送",
	}, ERROR_CODE_HAS_LOWER_LEVEL: {
		"zh": "只能删除最低等级的配置",
	}, ERROR_CODE_NO_RIGHT_ERROR: {
		"zh": "没有权限",
	}, ERROR_CODE_TASK_NO_EXIST_ERROR: {
		"zh": "定时任务不存在",
	}, ERROR_CODE_TASK_STATUS_ERROR: {
		"zh": "定时任务状态错误",
	}, ERROR_CODE_TASK_APPNAME_DIFFERENT_ERROR: {
		"zh": "定时任务AppName不一致",
	}, ERROR_CODE_AGENT_WITHDRAW_NO_ENOUGH: {
		"zh": "佣金提现金额不足",
	}, ERROR_CODE_AGENT_DECREASE_COMMISSION_FAILED: {
		"zh": "扣除用户佣金失败",
	}, ERROR_CODE_AGENT_WITHDRAW_ADD_RECORD_FAILED: {
		"zh": "增加佣金提现记录失败",
	}, ERROR_CODE_AGENT_WITHDRAW_UPDATE_RECORD_STATUS_FAILED: {
		"zh": "更新佣金提现记录状态失败",
	}, ERROR_CODE_AGENT_WITHDRAW_QUERY_RECORD_FAILED: {
		"zh": "查询佣金提现记录失败",
	}, ERROR_CODE_AGENT_WITHDRAW_CHECKED: {
		"zh": "该订单已经审核过了",
	}, ERROR_CODE_USER_REGISTERED: {
		"zh": "Email用户已存在",
	}, ERROR_CODE_RISK_ALERT: {
		"zh": "游戏风险报警",
	}, ERROR_CODE_GAME_REPORT_CAL: {
		"zh": "游戏报告错误计算",
	}, ERROR_CODE_GAME_DATA_HASED: {
		"zh": "今日数据已生成过",
	},
}
